# Generated by Django 5.1.5 on 2025-01-17 12:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_uz', models.CharField(max_length=100, null=True)),
                ('title_ru', models.CharField(max_length=100, null=True)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(max_length=5000)),
                ('description_uz', models.TextField(max_length=5000, null=True)),
                ('description_ru', models.TextField(max_length=5000, null=True)),
                ('description_en', models.TextField(max_length=5000, null=True)),
                ('pages', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20)])),
                ('published_date', models.DateField(auto_now=True)),
                ('ebook_version', models.FileField(upload_to='files/ebook')),
                ('file_format', models.CharField(choices=[('PDF', 'Pdf'), ('Epub', 'Epub')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sell_location', models.CharField(max_length=100)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
