# Generated by Django 5.1.5 on 2025-04-08 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ebook_version',
            field=models.FileField(blank=True, null=True, upload_to='files/ebook'),
        ),
        migrations.AlterField(
            model_name='book',
            name='file_format',
            field=models.CharField(blank=True, choices=[('PDF', 'Pdf'), ('Epub', 'Epub')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='sell_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
